services:
  - type: web
    name: telco-b2b-analytics
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app/main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
